SET FOREIGN_KEY_CHECKS=0;

INSERT INTO DS_BASE_LOGIN (
       ID,LOGINTIME,LOGOUTTIME,TIMEOUTTIME,PWDTIME,TICKET,IP,ACCOUNT,NAME,STATUS)
SELECT ID,LOGINTIME,LOGOUTTIME,TIMEOUTTIME,PWDTIME,TICKET,IP,ACCOUNT,NAME,STATUS from DS_COMMON_LOGIN;

INSERT INTO DS_BASE_USERTYPE (
       ID,NAME,ALIAS,STATUS,SEQ,MEMO,RESOURCES)
SELECT ID,NAME,ALIAS,STATUS,SEQ,MEMO,RESOURCES from DS_COMMON_USERTYPE;

INSERT INTO DS_BASE_USER (
       ID,STATUS,BM,SSQY,NAME,MOBILE,ACCOUNT,PASSWORD,WORKCARD,SEX,COUNTRY,PROVINCE,CITY,AVATAR,IDCARD,EMAIL,PHONE,ORGPID,ORGID,TYPE,TYPENAME,EXALIAS,EXNAME,CREATETIME,LASTTIME)
SELECT ID,STATUS,'',''  ,NAME,MOBILE,ACCOUNT,PASSWORD,WORKCARD,0  ,'',     '',      '',  '',    IDCARD,EMAIL,PHONE,ORGPID,ORGID,TYPE,TYPENAME,EXALIAS,EXNAME,CREATETIME,0        from DS_COMMON_USER;

INSERT INTO DS_BASE_SYSTEM (
       ID,NAME,ALIAS,PASSWORD,DOMAINURL,ROOTURL,MENUURL,STATUS,SEQ,MEMO)
SELECT ID,NAME,ALIAS,PASSWORD,DOMAINURL,ROOTURL,MENUURL,STATUS,SEQ,MEMO from DS_COMMON_SYSTEM;

update DS_BASE_SYSTEM set ALIAS='!portal'  where ALIAS='portal';
update DS_BASE_SYSTEM set ALIAS='base', ROOTURL=replace(ROOTURL,'DsCommon','base') where ALIAS='DsCommon';
update DS_BASE_SYSTEM set MENUURL='' where length(MENUURL) > 0;

INSERT INTO DS_BASE_FUNC (
       ID,PID,SYSTEMID,NAME,ALIAS,        URI,                           IMG,STATUS,SEQ,MEMO,RESOURCES)
SELECT ID,PID,SYSTEMID,NAME,ALIAS,replace(URI,'/ds/common/','/ds/base/'),IMG,STATUS,SEQ,MEMO,replace(RESOURCES,'/ds/common/','/ds/base/') from DS_COMMON_FUNC;
update DS_BASE_FUNC set URI=replace(URI,'getCommonLogin.jsp','getBaseLogin.jsp') where URI like '%/ds/base/log/getCommonLogin.jsp';

INSERT INTO DS_BASE_ROLE (
       ID,PID,SYSTEMID,NAME,SEQ,MEMO)
SELECT ID,PID,SYSTEMID,NAME,SEQ,MEMO from DS_COMMON_ROLE;

INSERT INTO DS_BASE_ROLEFUNC (
       ID,SYSTEMID,ROLEID,FUNCID)
SELECT ID,SYSTEMID,ROLEID,FUNCID from DS_COMMON_ROLEFUNC;

INSERT INTO DS_BASE_ORG (
       ID,PID,NAME,STATUS,SEQ,DUTYSCOPE,MEMO)
SELECT ID,PID,NAME,STATUS,SEQ,DUTYSCOPE,MEMO from DS_COMMON_ORG;

INSERT INTO DS_BASE_ORGROLE (
       ID,ORGID,ROLEID)
SELECT ID,ORGID,ROLEID from DS_COMMON_ORGROLE;

INSERT INTO DS_BASE_USERORG (
       ID,ORGID,USERID)
SELECT ID,ORGID,USERID from DS_COMMON_USERORG;

INSERT INTO DS_BASE_DICT (
       ID,NAME,LABEL,LEVEL,SEQ,UPDATETIME)
SELECT ID,NAME,LABEL,    0,SEQ,1 from DS_COMMON_DICT where STATUS=1;

INSERT INTO DS_BASE_DICT (
       ID,NAME,LABEL,LEVEL,SEQ,UPDATETIME)
SELECT ID,NAME,LABEL,    1,SEQ,1 from DS_COMMON_DICT where STATUS=0;

INSERT INTO DS_BASE_DICT_DATA (
         NAME,ID,     PID,      LABEL,  STATUS,  SEQ,  MEMO, LEVEL)
SELECT a.NAME,a.ALIAS,b.ALIAS,a.LABEL,a.STATUS,a.SEQ,a.MEMO, 0 from DS_COMMON_DICT_DATA a LEFT JOIN DS_COMMON_DICT_DATA b ON b.ID=a.PID;

update DS_BASE_DICT_DATA set LEVEL=1 where NAME in (select NAME from DS_BASE_DICT where LEVEL=1);

INSERT INTO DS_BASE_UNIT(ID, STATUS, NAME, APPID, APPSECRET, RETURNURL, TYPE, CREATETIME, LASTTIME, MEMO) VALUES (8800, 1, '门户', 'portal', 'portal321', '', 0, '2019-03-24 00:00:01', 8800, '');
INSERT INTO DS_BASE_UNIT(ID, STATUS, NAME, APPID, APPSECRET, RETURNURL, TYPE, CREATETIME, LASTTIME, MEMO) VALUES (8866, 1, '统一认证平台', 'base', 'base321', '', 0, '2019-03-24 00:00:01', 8855, '');



INSERT INTO DS_BASE_USER_BM (
       BM,           USERID,       TYPE)
SELECT ACCOUNT as BM,ID as USERID, 0 from DS_COMMON_USER;
